#ifdef __SNIPER

#ifndef __Q_SNIPERT_H
#define __Q_SNIPERT_H

#define SNIPER_CAL_PIX_UM_DEFZPOS	2.0
#define SNIPER_CAL_PIX_UM_DEFSIZE	5.0
#define MAX_VAR_SNIPER_CAL_PIX_UM	0.5
#define MAX_ERROR_SNIPER_CCAL		100 // um

#define ZPOSMAX       30
#define DELTASTEP     1
#define DELTASTEP1    20
#define ZPOS1OFF      30
#define ZPOS2OFF      30
#define DELTAZPOSMAX2 400

#define SCANDEF_MM    7


#define ALGO_SNIPER0_NAME_DEFAULT					"zero theta"
#define ALGO_SNIPER0_SEARCH_SPEED_DEFAULT			175
#define ALGO_SNIPER0_ACCEL_SPEED_DEFAULT			12300
#define ALGO_SNIPER0_ANGLE_LIMIT_DEFAULT			40
#define ALGO_SNIPER0_PREROTATION_ANGLE_DEFAULT		9
#define ALGO_SNIPER0_IGNORE_FINAL_FRAMES_DEFAULT	3
#define ALGO_SNIPER0_CODE_DEFAULT					1

#define ALGO_SNIPER1_NAME_DEFAULT					""
#define ALGO_SNIPER1_SEARCH_SPEED_DEFAULT			175
#define ALGO_SNIPER1_ACCEL_SPEED_DEFAULT			12300
#define ALGO_SNIPER1_ANGLE_LIMIT_DEFAULT			26
#define ALGO_SNIPER1_PREROTATION_ANGLE_DEFAULT		9
#define ALGO_SNIPER1_IGNORE_FINAL_FRAMES_DEFAULT	3
#define ALGO_SNIPER1_CODE_DEFAULT					1

#define ALGO_SNIPER2_NAME_DEFAULT					""
#define ALGO_SNIPER2_SEARCH_SPEED_DEFAULT			175
#define ALGO_SNIPER2_ACCEL_SPEED_DEFAULT			12300
#define ALGO_SNIPER2_ANGLE_LIMIT_DEFAULT			26
#define ALGO_SNIPER2_PREROTATION_ANGLE_DEFAULT		9
#define ALGO_SNIPER2_IGNORE_FINAL_FRAMES_DEFAULT	3
#define ALGO_SNIPER2_CODE_DEFAULT					2

#define ALGO_SNIPER3_NAME_DEFAULT					""
#define ALGO_SNIPER3_SEARCH_SPEED_DEFAULT			175
#define ALGO_SNIPER3_ACCEL_SPEED_DEFAULT			12300
#define ALGO_SNIPER3_ANGLE_LIMIT_DEFAULT			30
#define ALGO_SNIPER3_PREROTATION_ANGLE_DEFAULT		10
#define ALGO_SNIPER3_IGNORE_FINAL_FRAMES_DEFAULT	3
#define ALGO_SNIPER3_CODE_DEFAULT					1


#endif

#endif
